name: 'build'
on: pull_request

jobs:
  build:
    # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: lts/-1

      - name: Install dependencies
        run: |
          npm install

      - name: ESLint
        run: |
          npm run lint

      - name: TSC & Vite build
        run: |
          npm run build
